name: watch_connectivity_example
description: Demonstrates how to use the watch_connectivity plugin.
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  watch_connectivity:
    # When depending on this package from a real application you should use:
    #   watch_connectivity: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^2.0.1

flutter:
  uses-material-design: true
