name: watch_connectivity_platform_interface
description: Platform interface for communicating with wearable watch devices
version: 0.1.0
homepage: https://github.com/Rexios80/watch_connectivity

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  rexios_lints: ^2.0.0
