name: watch_connectivity_platform_interface
description: Platform interface for communicating with wearable watch devices
version: 0.4.0
homepage: https://github.com/Rexios80/watch_connectivity/tree/master/watch_connectivity_platform_interface

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rexios_lints: ^17.0.2
