name: watch_connectivity_garmin
description: Implementation of watch_connectivity for use with Garmin devices
version: 0.1.0
homepage: https://github.com/Rexios80/watch_connectivity

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  
  watch_connectivity:
    path: ../watch_connectivity

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.watch_connectivity_garmin
        pluginClass: WatchConnectivityGarminPlugin
      ios:
        pluginClass: WatchConnectivityGarminPlugin
