name: watch_connectivity_garmin
description: Wrapper for the ConnectIQ SDK to communicate with Garmin watches
version: 0.1.0
homepage: https://github.com/Rexios80/watch_connectivity/tree/master/watch_connectivity_garmin

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  
  watch_connectivity_platform_interface:
    path: ../watch_connectivity_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.watch_connectivity_garmin
        pluginClass: WatchConnectivityGarminPlugin
      ios:
        pluginClass: WatchConnectivityGarminPlugin
