name: watch_connectivity_garmin
description: Wrapper for the ConnectIQ SDK to communicate with Garmin watches
version: 0.1.8
homepage: https://github.com/Rexios80/watch_connectivity/tree/master/watch_connectivity_garmin

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  recase: ^4.1.0
  watch_connectivity_platform_interface: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^17.0.2

# dependency_overrides:
#   watch_connectivity_platform_interface:
#     path: ../watch_connectivity_platform_interface

flutter:
  plugin:
    platforms:
      android:
        package: dev.rexios.watch_connectivity_garmin
        pluginClass: WatchConnectivityGarminPlugin
      ios:
        pluginClass: WatchConnectivityGarminPlugin
